language: c
compiler:
  - gcc
  - clang
os:
  - linux
  
addons:
  apt:
    packages:
    - libglew-dev
    - libglu1-mesa-dev
    - libx11-dev
    - libxrandr-dev
    - libxinerama-dev
    - libxi-dev
    - libtool
    - automake
    - check
  
script: ./configure && make && make check
